title: "G-nyang's Portfolio"
description: "Data Analysis · Hiking · Freediving · Digital Nomad"
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
author: G-nyang
markdown: kramdown
